spring:
  application:
    name: websocket-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/users_websocket_db
    driver-class-name: org.postgresql.Driver
    password: qwer
    username: raidenz

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  threads:
    virtual:
      enabled: true


#server:
#  address: 0.0.0.0
